### ISSUE TITLE
python -m firmrec.pipeline all执行报错

### ISSUE THREAD

**Issue by glkfc** [seclab-fudan/FirmRec#2]
从拉取的docker中执行`python -m firmrec.pipeline all`报错，如下所示
```
root@b85c5e71fdec:~# python -m firmrec.pipeline all
Traceback (most recent call last):
  File "/root/miniconda/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/firmrec/pipeline/__main__.py", line 1, in <module>
    from .gen_cmds import firmrec_main
  File "/root/firmrec/pipeline/gen_cmds.py", line 19, in <module>
    from ..econfig import ExperimentConfig, econfig
  File "/root/firmrec/econfig.py", line 156, in <module>
    econfig = ExperimentConfig.load(ConstPaths.EXPERIMENT_CONFIG_PATH)
  File "/root/firmrec/econfig.py", line 30, in load
    return cls(config)
  File "/root/firmrec/econfig.py", line 12, in __init__
    super().__init__(raw_config)
TypeError: object.__init__() takes exactly one argument (the instance to initialize)
```

**Comment by Haoyu-Xiao** [comment]
需要先执行`make build`重新构建docker image，然后通过`make start`启动docker
